### ISSUE TITLE
Java call graph generation and output sometimes consumes excessive memory (tracking list)

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#196]
## Describe the issue
Generating call graphs and outputting them (to JSON) consumes excessive memory and then fails. This issue is meant to keep track of such cases.

## To reproduce
```
ExtendedRevisionJavaCallGraph rcg = cg.generate(jarFile, "", "CHA", true);
```

## Examples
Coordinate | VM heap memory | FASTEN version | CG | output | available at KB
-------------|---------------------|-------------------|-----|--------|--------
it.unimi.dsi:fastutil:8.4.4 | 24G | e8e99a97 | pass | crash | no

## Expected behavior
Call graph generation succeeds and produces a file (JSON or other format).

## Logs
```
[2021-01-14 23:21:24,653] [INFO ] [main] [e.f.c.m.CallGraphUtils] - Writing graph to target\callgraphs\fastutil-8.4.4.jar.json
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:748)
	at java.base/java.lang.StringBuffer.append(StringBuffer.java:424)
	at java.base/java.io.StringWriter.write(StringWriter.java:77)
	at org.json.JSONObject.indent(JSONObject.java:2452)
```

## Environment (please complete the following information):
 - OS: Windows 10
 - Java version: 11

**Comment by MagielBruntink** [comment]
Seems fixed since 2ef621844b8d15c172496a4f0ba6e645aa5b7723, closing for now.
