### ISSUE TITLE
Local merger crashes with java.lang.IllegalArgumentException: value already present

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#209]
## Describe the bug
For some Maven artifacts, the local merger crashes with java.lang.IllegalArgumentException: value already present. This happens at least for the artifacts listed below, with callgraphs attached. These were generated with the latest version of JavaCGOpal (28 Jan 2021 EOD).

[info.picocli.picocli-4.0.4.json.zip](https://github.com/fasten-project/fasten/files/5889399/info.picocli.picocli-4.0.4.json.zip)
[net.bytebuddy.byte-buddy-1.10.5.json.zip](https://github.com/fasten-project/fasten/files/5889631/net.bytebuddy.byte-buddy-1.10.5.json.zip)
[org.apache.kafka.kafka-clients-2.3.0.json.zip](https://github.com/fasten-project/fasten/files/5889695/org.apache.kafka.kafka-clients-2.3.0.json.zip)

## To Reproduce
Read in the attached call graph, put it in a depSet array, run the local merger.

```
var rcg = new ExtendedRevisionJavaCallGraph(new JSONObject(Files.readString(Path.of("info.picocli.picocli-4.0.4.json"))));
var depSet = new List<ExtendedRevisionJavaCallGraph>;
depSet.add(rcg);
var merger = new LocalMerger(depSet);
merger.mergeAllDeps();
```

## Expected behavior
No exception, a nicely merged call graph :-)

## Logs
```
[2021-01-28 19:33:17,657] [INFO ] [main] [e.f.r.CallGraphMerger] - Read target\callgraphs\info.picocli.picocli-4.0.4.json(2246 nodes).
java.lang.IllegalArgumentException: value already present: JavaType{sourceFileName='picocli/CommandLine.java', methods={}, superClasses=[/java.lang/Object], superInterfaces=[/java.lang.annotation/Annotation], access=public, final=false}
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:289)
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:270)
	at java.base/java.util.AbstractMap.putAll(AbstractMap.java:281)
	at com.google.common.collect.HashBiMap.create(HashBiMap.java:83)
	at eu.fasten.core.merge.LocalMerger.mergeWithCHA(LocalMerger.java:235)
	at eu.fasten.core.merge.LocalMerger.mergeAllDeps(LocalMerger.java:156)
	at eu.fasten.rapid.CallGraphMerger.mergeCallGraphs(CallGraphMerger.java:63)
	at eu.fasten.rapid.CallGraphMerger.run(CallGraphMerger.java:52)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at eu.fasten.rapid.CallGraphMerger.main(CallGraphMerger.java:45)
```

## Environment (please complete the following information):
 - OS: Windows 10
 - Java version: 11

**Comment by MagielBruntink** [comment]
Dear @ashkboos could you please look into this issue? It is currently blocking our progress with local analysis.

**Comment by ashkboos** [comment]
@MagielBruntink Is this fixed now?

**Comment by MagielBruntink** [comment]
Hi @ashkboos yes it is, thank you!
