### ISSUE TITLE
POM Analyzer crashes with coordinate: org.apache.commons:commons-compress:1.3

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#210]
## Describe the bug
POM Analyzer crashes unexpectedly while processing the maven coordinate org.apache.commons:commons-compress:1.3

## To Reproduce
1. Clone https://github.com/fasten-project/fasten-docker-deployment
2. docker-compose up (wait until everything is up)
3. `$ echo "org.apache.commons:commons-compress:1.3|{"groupId":"org.apache.commons","artifactId":"commons-compress","version":"1.3"}" | docker-compose exec -T kafka kafka-console-producer --broker-list kafka:19092 --topic fasten.mvn.test --property 'parse.key=true' --property 'key.separator=|'`
4. Inspect log of POM Analyzer in local Docker client.

## Expected behavior
No crash :-)

## Logs
```
[2021-01-29 16:12:34,497] [INFO ] [main] [e.f.a.p.POMAnalyzerPlugin$POMAnalyzer] - Consumed: {groupId:org.apache.commons,artifactId:commons-compress,version:1.3}
[2021-01-29 16:12:34,502] [ERROR] [main] [e.f.s.p.k.FastenKafkaPlugin] - Error occurred while processing call graphs
org.json.JSONException: JSONObject["version"] not a string.
at org.json.JSONObject.getString(JSONObject.java:855)
at eu.fasten.analyzer.pomanalyzer.POMAnalyzerPlugin$POMAnalyzer.consume(POMAnalyzerPlugin.java:111)
at eu.fasten.server.plugins.kafka.FastenKafkaPlugin.processRecord(FastenKafkaPlugin.java:235)
at eu.fasten.server.plugins.kafka.FastenKafkaPlugin.handleConsuming(FastenKafkaPlugin.java:179)
at eu.fasten.server.plugins.kafka.FastenKafkaPlugin.run(FastenKafkaPlugin.java:142)
at eu.fasten.server.plugins.kafka.FastenKafkaPlugin.start(FastenKafkaPlugin.java:160)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at eu.fasten.server.FastenServer.run(FastenServer.java:205)
at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
at picocli.CommandLine.access$1100(CommandLine.java:145)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
at picocli.CommandLine.execute(CommandLine.java:2058)
at eu.fasten.server.FastenServer.main(FastenServer.java:342)
[2021-01-29 16:12:34,503] [INFO ] [main] [o.a.k.c.c.i.AbstractCoordinator] - [Consumer clientId=eu.fasten.analyzer.pomanalyzer.POMAnalyzerPlugin.POMAnalyzer_client, groupId=eu.fasten.analyzer.pomanalyzer.POMAnalyzerPlugin.POMAnalyzer] Member eu.fasten.analyzer.pomanalyzer.POMAnalyzerPlugin.POMAnalyzer_client-e48591f0-163e-4f9f-8c6b-294731bf5446 sending LeaveGroup request to coordinator kafka:19092 (id: 2147483646 rack: null)
[2021-01-29 16:12:34,511] [INFO ] [main] [e.f.s.p.k.FastenKafkaPlugin] - Plugin POM Analyzer plugin stopped
```
## Environment (please complete the following information):
 - OS: Docker 
 - Java version: 11

**Comment by MagielBruntink** [comment]
This issue was caused the input being malformed, not the Maven coordinate. Related to https://github.com/fasten-project/fasten/issues/215#issue-797776665 , closing this issue.
