### ISSUE TITLE
API: endpoint for transitive vulnerabilities

### ISSUE THREAD

**Issue by romatallinn** [fasten-project/fasten#227]
## Description
Although endpoint for transitive vulnerabilities is present in API, it is currently not working.

For example,

**GET** `https://api.fasten-project.eu/api/__INTERNAL__/packages/org.springframework.boot:spring-boot-starter/1.5.14.RELEASE/vulnerabilities` returns `500`.

Some other packages are getting timeout exceptions.

## Solution
The endpoint must return the list of transitive(!) vulnerabilities for a specific package; incl. paths to these vulnerabilities.

**Comment by wzorgdrager** [comment]
The related log to this 500 error:
```
2021-02-04 19:26:48.116 DEBUG 1 --- [nio-8080-exec-6] o.s.web.servlet.DispatcherServlet        : GET "/__INTERNAL__/packages/org.springframework.boot:spring-boot-starter/1.5.14.RELEASE/vulnerabilities", parameters={}
2021-02-04 19:26:48.117 DEBUG 1 --- [nio-8080-exec-6] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to eu.fasten.analyzer.restapiplugin.mvn.api.StitchingApi#getTransitiveVulnerabilities(String, String)
2021-02-04 19:26:48.147  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 1886677 could not be found
2021-02-04 19:26:48.147 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 1886677
2021-02-04 19:26:48.148  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 3134820 could not be found
2021-02-04 19:26:48.148 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 3134820
2021-02-04 19:26:48.148  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 505196 could not be found
2021-02-04 19:26:48.148 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 505196
2021-02-04 19:26:48.148  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 2607272 could not be found
2021-02-04 19:26:48.148 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 2607272
2021-02-04 19:26:48.151  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 2481309 could not be found
2021-02-04 19:26:48.151 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 2481309
2021-02-04 19:26:48.151  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 1968196 could not be found
2021-02-04 19:26:48.151 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 1968196
2021-02-04 19:26:48.151  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 3117301 could not be found
2021-02-04 19:26:48.151 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 3117301
2021-02-04 19:26:48.151  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 1552332 could not be found
2021-02-04 19:26:48.151 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 1552332
2021-02-04 19:26:48.152  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 3094961 could not be found
2021-02-04 19:26:48.152 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 3094961
2021-02-04 19:26:48.343  INFO 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Created the Universal CHA with 1768 vertices in 0.201
2021-02-04 19:26:48.345  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 1886677 could not be found
2021-02-04 19:26:48.345 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 1886677
2021-02-04 19:26:48.345  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 3134820 could not be found
2021-02-04 19:26:48.345 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 3134820
2021-02-04 19:26:48.345  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 505196 could not be found
2021-02-04 19:26:48.345 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 505196
2021-02-04 19:26:48.345  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 2607272 could not be found
2021-02-04 19:26:48.345 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 2607272
2021-02-04 19:26:48.347  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 2481309 could not be found
2021-02-04 19:26:48.347 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 2481309
2021-02-04 19:26:48.347  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 1968196 could not be found
2021-02-04 19:26:48.347 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 1968196
2021-02-04 19:26:48.347  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 3117301 could not be found
2021-02-04 19:26:48.347 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 3117301
2021-02-04 19:26:48.347  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 1552332 could not be found
2021-02-04 19:26:48.347 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 1552332
2021-02-04 19:26:48.348  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 3094961 could not be found
2021-02-04 19:26:48.348 ERROR 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Couldn't retrieve a call graph with ID: 3094961
2021-02-04 19:26:48.695  INFO 1 --- [nio-8080-exec-6] eu.fasten.core.merge.DatabaseMerger      : Created the type dictionary with 1820 types in 0.352 seconds
2021-02-04 19:26:48.697  WARN 1 --- [nio-8080-exec-6] eu.fasten.core.data.graphdb.RocksDao     : Graph with index 2922475 could not be found
2021-02-04 19:26:48.698 DEBUG 1 --- [nio-8080-exec-6] o.s.web.servlet.DispatcherServlet        : Failed to complete request: java.lang.NullPointerException
2021-02-04 19:26:48.699 ERROR 1 --- [nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at eu.fasten.core.merge.DatabaseMerger.createTypeMap(DatabaseMerger.java:410) ~[core-0.0.1-SNAPSHOT.jar!/:na]
	at eu.fasten.core.merge.DatabaseMerger.mergeWithCHA(DatabaseMerger.java:215) ~[core-0.0.1-SNAPSHOT.jar!/:na]
	at eu.fasten.core.merge.DatabaseMerger.mergeWithCHA(DatabaseMerger.java:203) ~[core-0.0.1-SNAPSHOT.jar!/:na]
	at eu.fasten.analyzer.restapiplugin.mvn.api.impl.StitchingApiServiceImpl.getTransitiveVulnerabilities(StitchingApiServiceImpl.java:167) ~[classes!/:na]
	at eu.fasten.analyzer.restapiplugin.mvn.api.StitchingApi.getTransitiveVulnerabilities(StitchingApi.java:62) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) ~[tomcat-embed-core-9.0.39.jar!/:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.39.jar!/:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.39.jar!/:9.0.39]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

2021-02-04 19:26:48.700 DEBUG 1 --- [nio-8080-exec-6] o.s.web.servlet.DispatcherServlet        : "ERROR" dispatch for GET "/error", parameters={}
2021-02-04 19:26:48.700 DEBUG 1 --- [nio-8080-exec-6] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController#errorHtml(HttpServletRequest, HttpServletResponse)
2021-02-04 19:26:48.704 DEBUG 1 --- [nio-8080-exec-6] o.s.w.s.v.ContentNegotiatingViewResolver : Selected 'text/html' given [text/html, text/html;q=0.8]
2021-02-04 19:26:48.704 DEBUG 1 --- [nio-8080-exec-6] o.s.web.servlet.DispatcherServlet        : Exiting from "ERROR" dispatch, status 500
```

**Comment by MihhailSokolov** [comment]
I've increased a timeout to 1 minute (fb7c478) and implemented a more efficient but less precise way of finding the vulnerable paths (675bac3) - now it will stitch only those transitive dependencies that are in any path to any vulnerable dependency instead of stitching everything. Hopefully, this resolves this issue.
P.S. I cannot really do anything useful regarding that 500 error because it is caused by the stitching algorithm when it cannot find the artifact.

**Comment by romatallinn** [comment]
> it is caused by the stitching algorithm when it cannot find the artifact.

Does it throw an exception? Maybe we can try-catch it and then ignore it in order to escape `500` error? So we have at least some response to work with.

**Comment by romatallinn** [comment]
@ashkboos @proksch I'm still wandering around not able to do anything with the issue.

I see that it takes indeed quite a lot of time to stitch the graphs. I'm not able to say, however, if the problem is in the input or the stitching algorithm. I desperately need help.

Moreover, note the second screenshot; the line `Created depSet (0), depIds (0), vulnerableDependencies (0)`. It indicates that the graph is empty, which is not the problem by itself, but even then it takes 117 seconds to stitch something.

<img width="769" alt="Screenshot 2021-02-27 at 00 15 33" src="https://user-images.githubusercontent.com/14923964/109571063-5eb8ba80-7aeb-11eb-80fd-f4dced815d13.png">

<img width="788" alt="Screenshot 2021-03-02 at 00 04 42" src="https://user-images.githubusercontent.com/14923964/109571069-61b3ab00-7aeb-11eb-8cad-4f5b31003b61.png">

<img width="788" alt="Screenshot 2021-03-02 at 00 04 42" src="https://user-images.githubusercontent.com/14923964/109571071-624c4180-7aeb-11eb-862d-4974afb37501.png">

**Comment by proksch** [comment]
@MihhailSokolov Do you have any input on that? Is this an artifact of your optimized dependency resolution? Do you have an idea why stitching of an empty depset would still take more than 2min?

**Comment by ashkboos** [comment]
@romatallinn is this issue still relevant?

**Comment by romatallinn** [comment]
@ashkboos nope/
