### ISSUE TITLE
mergeWithCHA() throws NullPointerException and OutOfMemoryError

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#231]
The release of the prototype search engine has made running a large number of stitching easy and necessary. But trying to run a coreachability query on a popular package like commons-lang3 yields several instances of NullPointerException and OutOfMemoryError from mergeWithCHA(). These can be easily replicated by checking out the "se" branch, and running the search engine on tehran:
```
export PGPASSWORD=fasten
rlwrap java eu.fasten.core.search.SearchEngine jdbc:postgresql://monster:5432/fasten_java fastenro /mnt/fasten/graphdb/ resolver
```
For example, the query
```
-fasten://org.apache.commons:commons-lang3$3.0
```
yields
```
java.lang.NullPointerException: null
	at eu.fasten.core.merge.DatabaseMerger.createTypeMap(DatabaseMerger.java:410)
	at eu.fasten.core.merge.DatabaseMerger.mergeWithCHA(DatabaseMerger.java:215)
	at eu.fasten.core.merge.DatabaseMerger.mergeWithCHA(DatabaseMerger.java:203)
	at eu.fasten.core.search.SearchEngine.to(SearchEngine.java:586)
	at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:506)
	at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:491)
	at eu.fasten.core.search.SearchEngine.main(SearchEngine.java:680)
```
This looks simply like a missing check on missing graph data. The search engine catches all these exceptions and shows them after the results.

However, it also yields
```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:242)
	at java.base/java.util.ArrayList.add(ArrayList.java:485)
	at java.base/java.util.ArrayList.add(ArrayList.java:498)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1980)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:155)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:214)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4192)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:279)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:375)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:333)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2880)
	at eu.fasten.core.merge.DatabaseMerger.getArcs(DatabaseMerger.java:358)
	at eu.fasten.core.merge.DatabaseMerger.mergeWithCHA(DatabaseMerger.java:216)
	at eu.fasten.core.merge.DatabaseMerger.mergeWithCHA(DatabaseMerger.java:203)
	at eu.fasten.core.search.SearchEngine.to(SearchEngine.java:586)
	at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:506)
	at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:491)
	at eu.fasten.core.search.SearchEngine.main(SearchEngine.java:680)
```
This seems to be triggered by a _monstre_ SQL query over all arcs of the graph fetched here
```
	at eu.fasten.core.merge.DatabaseMerger.getArcs(DatabaseMerger.java:358)
```
Probably a lazy approach could fix the issue. Catching is out of question as OutOfMemoryErrors usually crash the JVM, even if one is catching all throwables.

**Comment by ilyagrishkov** [comment]
Records are now fetched in batches of size 10000. OutOfMemoryError should be solved now.

**Comment by ilyagrishkov** [comment]
NullPointerException should no longer be thrown, rather `mergeWithCHA()` method will return `null` if artifact is not present in GraphDB

**Comment by vigna** [comment]
Did you try the replication instructions? Because presently we still have

```
java.lang.NullPointerException: null
	at eu.fasten.core.merge.DatabaseMerger.createTypeMap(DatabaseMerger.java:410)
	at eu.fasten.core.merge.DatabaseMerger.mergeWithCHA(DatabaseMerger.java:215)
	at eu.fasten.core.merge.DatabaseMerger.mergeWithCHA(DatabaseMerger.java:203)
	at eu.fasten.core.search.SearchEngine.getStitchedGraph(SearchEngine.java:344)
	at eu.fasten.core.search.SearchEngine.to(SearchEngine.java:624)
	at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:544)
	at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:529)
	at eu.fasten.core.search.SearchEngine.main(SearchEngine.java:713)
```

for the same query as above.

Note that to replicate you now have to use a different JDBC URI: `jdbc:postgresql://172.16.45.123/fasten_java`

**Comment by ilyagrishkov** [comment]
New changes have been merged to `develop` branch. From this stacktrace I can see that you are still running the old version. I checked `se` branch and it doesn’t have any of the latest changes to dbMerge. Please merge `develop` into your branch and try again. Let me know if something doesn’t work.

**Comment by vigna** [comment]
Argh. Out of habitude, I merged with master. I forgot we have a master called develop. 😂

**Comment by vigna** [comment]
OK. Now we get the remainder from Postgres
```
A fetch size of 10000 was set on a auto-commit PostgreSQL connection, which is not recommended. See http://jdbc.postgresql.org/documentation/head/query.html#query-with-cursor
```
As I already explained in the meeting, lazy iterating over the result is the correct way to handle this.

**Comment by vigna** [comment]
With the new modifications, we get 
```
2021-02-15 13:33:36,817 382629 INFO [main] e.f.c.m.DatabaseMerger - Created the type dictionary with 5248 types in 0.782 seconds
2021-02-15 13:33:37,175 382987 INFO [main] o.j.i.AbstractResultQuery - Fetch Size               : A fetch size of 10000 was set on a auto-commit PostgreSQL connection, which is not recommended. See http://jdbc.postgresql.org/documentation/head/query.html#query-with-cursor
2021-02-15 13:52:30
Full thread dump OpenJDK 64-Bit Server VM (11.0.1+13 mixed mode):

Threads class SMR info:
_java_thread_list=0x00007ff5340d1e10, length=9, elements={
0x00007ff5e0019800, 0x00007ff5e06ff800, 0x00007ff5e0703800, 0x00007ff5e0716000,
0x00007ff5e0718800, 0x00007ff5e071a800, 0x00007ff5e071c800, 0x00007ff5e07ac000,
0x00007ff5e07c1000
}

"main" #1 prio=5 os_prio=0 cpu=184072.54ms elapsed=1516.14s tid=0x00007ff5e0019800 nid=0x2de86 runnable  [0x00007ff5e84fb000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(java.base@11.0.1/Native Method)
	at java.net.SocketInputStream.socketRead(java.base@11.0.1/SocketInputStream.java:115)
	at java.net.SocketInputStream.read(java.base@11.0.1/SocketInputStream.java:168)
	at java.net.SocketInputStream.read(java.base@11.0.1/SocketInputStream.java:140)
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:143)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:112)
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:70)
	at org.postgresql.core.PGStream.ReceiveChar(PGStream.java:283)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1799)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	- locked <0x0000000083e81ef0> (a org.postgresql.core.v3.QueryExecutorImpl)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:155)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:214)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4192)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:279)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:375)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:481)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:450)
	at org.jooq.impl.AbstractResultQuery.lambda$fetchStream$1(AbstractResultQuery.java:421)
	at org.jooq.impl.AbstractResultQuery$$Lambda$127/0x0000000800324c40.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(java.base@11.0.1/ReferencePipeline.java:271)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(java.base@11.0.1/Streams.java:411)
	at java.util.stream.AbstractPipeline.copyInto(java.base@11.0.1/AbstractPipeline.java:484)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@11.0.1/AbstractPipeline.java:474)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(java.base@11.0.1/ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(java.base@11.0.1/ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(java.base@11.0.1/AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(java.base@11.0.1/ReferencePipeline.java:497)
	at eu.fasten.core.merge.DatabaseMerger.mergeWithCHA(DatabaseMerger.java:234)
	at eu.fasten.core.search.SearchEngine.getStitchedGraph(SearchEngine.java:344)
	at eu.fasten.core.search.SearchEngine.to(SearchEngine.java:624)
	at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:548)
	at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:533)
	at eu.fasten.core.search.SearchEngine.main(SearchEngine.java:714)
```

The code has been stuck for 20 minutes inside the arcs.forEach() iteration at line 234 of DatabaseMerger. After a little more time,
```
2021-02-15 13:58:02,058 1847870 INFO [main] e.f.c.m.DatabaseMerger - Stitched in 1464.909 seconds
```

This will need to be addressed if we intend to do ecosystem-wide searches as planned.

**Comment by ilyagrishkov** [comment]
I will set auto commit to false for the dbMerge Postgres connection to avoid this remainder. 

The second issue seems more serious. Did it output the stitched call graph after 1464 seconds or did it fail completely?

**Comment by vigna** [comment]
It did output—see the last line of log I reported.

However, OutOfMemoryErrors still happen:
```
2021-02-15 14:07:56,302 2442114 INFO [main] e.f.c.m.DatabaseMerger - Created the type dictionary with 3411 types in 0.520 seconds
2021-02-15 14:07:56,556 2442368 INFO [main] o.j.i.AbstractResultQuery - Fetch Size               : A fetch size of 10000 was set on a auto-commit PostgreSQL connection, which is not recommended. See http://jdbc.postgresql.org/documentation/head/query.html#query-with-cursor
2021-02-15 14:10:47,818 2613630 ERROR [main] e.f.c.s.SearchEngine - mergeWithCHA threw an exception
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:242)
	at java.base/java.util.ArrayList.add(ArrayList.java:485)
	at java.base/java.util.ArrayList.add(ArrayList.java:498)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1980)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:155)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:214)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4192)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:279)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:375)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:481)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:450)
	at org.jooq.impl.AbstractResultQuery.lambda$fetchStream$1(AbstractResultQuery.java:421)
	at org.jooq.impl.AbstractResultQuery$$Lambda$127/0x0000000800324c40.apply(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at eu.fasten.core.merge.DatabaseMerger.mergeWithCHA(DatabaseMerger.java:234)
	at eu.fasten.core.search.SearchEngine.getStitchedGraph(SearchEngine.java:344)
	at eu.fasten.core.search.SearchEngine.to(SearchEngine.java:624)
	at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:548)
	at eu.fasten.core.search.SearchEngine.toRevision(SearchEngine.java:533)
	at eu.fasten.core.search.SearchEngine.main(SearchEngine.java:714)
```

**Comment by vigna** [comment]
BTW, the very first paragraph of `fetchSize()`'s documentation states clearly:
```
     * Regardless of this setting, {@link #fetchLazy()} is the only way in jOOQ
     * not to fetch all data in memory. However, you may influence how your JDBC
     * driver interacts with your database through specifying a fetch size.
```
So, once again: lazy is the only way to make this work.

**Comment by ilyagrishkov** [comment]
> BTW, the very first paragraph of `fetchSize()`'s documentation states clearly:
> 
> ```
>      * Regardless of this setting, {@link #fetchLazy()} is the only way in jOOQ
>      * not to fetch all data in memory. However, you may influence how your JDBC
>      * driver interacts with your database through specifying a fetch size.
> ```
> 
> So, once again: lazy is the only way to make this work.

`fetchLazy()` method is not the only way to. Alternatively one can fetch Stream and it will allow for lazy fetching as far as I understand. 
https://www.jooq.org/doc/3.2/manual/sql-execution/fetching/lazy-fetching-with-streams/

**Comment by vigna** [comment]
OK, so the jOOQ documentation is wrong and you know better.

Good luck with the OOM.

**Comment by proksch** [comment]
As Ilya has rightfully pointed out from the documentation, it sounds like `fetchStream` could be another valid solution... If you think that this is not the case, then please enlighten us. Another option is that -maybe- you guys just found an inconsistency in the jOOQ documentation and this should be reported. In any case, lashing out like this does not seem to be a nice way to treat someone that tries to help you.

Up to this point, the discussion seemed to be constructive and goal oriented. I think we should try to keep it that way.

**Comment by vigna** [comment]
`fetchStream()` is what presently is used the code (line 369 of DatabaseMerger.java). 

`fetchStream()` is still throwing an out-of-memory exception.

Our development is, of course, blocked.

You seem to be much more than experienced with me with jOOQ (I just learned !), so I'll let you guys take it from here. Sorry for any misunderstandings. :)

**Comment by proksch** [comment]
Dear @vigna, sorry to hear that you are feeling this way. I can neither understand, nor endorse your reaction though and I really do not appreciate the passive-aggressive tone of your comments. If you want to move on, fine, I will consider this issue solved. Feel free to re-open, if you plan to work on an actual fix together.

**Comment by vigna** [comment]
I have reported an outstanding out-of-memory error. There are specific instructions to reproduce the problem.

Please close issues when issues are actually closed. Aggressive behavior should be avoided in these discussions.

At present, mergeWithCHA() reproducibly throws an out-of-memory error and kills the JVM. We would be appreciate if you could solve this problem.

**Comment by proksch** [comment]
> ... Aggressive behavior should be avoided in these discussions. ...

I am not going to comment on that, I will leave the judgment of the situation to others.

**Comment by vigna** [comment]
The current implementation using `fetchLazy()` has solved the OOM problem. However, the code now on some graphs throws NullPointerExceptions that are hidden by a catch clause as discussed in #246.
