### ISSUE TITLE
POM Analyzer cannot be started with --local-storage

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#247]
## Describe the bug
Starting POM Analyzer with --local-storage results in error message that POD_INSTANCE_ID is not set, even if it is.

## Logs
```
[2021-02-19 15:27:03,590] [INFO ] [main] [o.a.k.c.u.AppInfoParser] - Kafka startTimeMs: 1613748423589
java.lang.IllegalArgumentException: Trying to initialize local storage but $POD_INSTANCE_ID is not in the environemnt variables.
at eu.fasten.server.plugins.kafka.LocalStorage.<init>(LocalStorage.java:27)
at eu.fasten.server.plugins.kafka.FastenKafkaPlugin.<init>(FastenKafkaPlugin.java:115)
at eu.fasten.server.plugins.kafka.FastenKafkaPlugin.<init>(FastenKafkaPlugin.java:129)
at eu.fasten.server.FastenServer.lambda$setupKafkaPlugins$9(FastenServer.java:239)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
at eu.fasten.server.FastenServer.setupKafkaPlugins(FastenServer.java:240)
at eu.fasten.server.FastenServer.run(FastenServer.java:203)
at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
at picocli.CommandLine.access$1100(CommandLine.java:145)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
at picocli.CommandLine.execute(CommandLine.java:2058)
at eu.fasten.server.FastenServer.main(FastenServer.java:342)
```
## Environment (please complete the following information):
 - OS: Docker
 - Java version: 11

**Comment by MagielBruntink** [comment]
This turned out to be a configuration error on my end.
