### ISSUE TITLE
NullPointerException in server Pod

### ISSUE THREAD

**Issue by marcomicera** [fasten-project/fasten#262]
## Describe the bug
The Fasten server Pod exits with error code 1 due to a NullPointerException (see the logs below).

## To Reproduce
1. All the steps of [this paragraph](https://github.com/fasten-project/fasten/wiki/Building-FASTEN-Docker-images#using-github-packages-to-pull-fasten-images), i.e.:
    ```shell script
    cat <<EOF | kubectl --namespace fasten create -f -
    apiVersion: v1
    kind: Pod
    metadata:
    name: fasten-server
    spec:
    containers:
    - name: fasten-server
        image: docker.pkg.github.com/fasten-project/fasten/fasten.server:latest
    imagePullSecrets:
    - name: fasten.docker.registry
    EOF
    ```

## Expected behavior
I guess the Pod's container should exit with code 0.

## Logs

-   `kubectl --namespace fasten logs fasten-server fasten-server`
    <details>
    <summary>Click to expand</summary>
    
    ```
    14:49:29.601 [main] INFO eu.fasten.server.FastenServer - FASTEN server started in development mode
    14:49:29.604 [main] DEBUG eu.fasten.server.FastenServer - Loading plugins from: ./plugins
    14:49:29.626 [main] INFO org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
    14:49:29.626 [main] INFO org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
    14:49:29.631 [main] INFO org.pf4j.DefaultPluginManager - PF4J version 0.0.0 in 'deployment' mode
    14:49:29.631 [main] DEBUG org.pf4j.AbstractPluginManager - Lookup plugins in './plugins'
    14:49:29.632 [main] DEBUG org.pf4j.AbstractPluginManager - Found 5 possible plugins: [./plugins/javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/metadata-plugin-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/graph-plugin-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/pom-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/repo-cloner-plugin-0.0.1-SNAPSHOT-with-dependencies.jar]
    14:49:29.633 [main] DEBUG org.pf4j.AbstractPluginManager - Use 'org.pf4j.ManifestPluginDescriptorFinder@49b0b76' to find plugins descriptors
    14:49:29.633 [main] DEBUG org.pf4j.AbstractPluginManager - Finding plugin descriptor for plugin './plugins/javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.674 [main] DEBUG org.pf4j.AbstractPluginManager - Found descriptor PluginDescriptor [pluginId=opal-plugin, pluginClass=eu.fasten.analyzer.javacgopal.OPALPlugin, version=0.0.1, provider=null, dependencies=[], description=Given a Maven coordinate or a file,                                           generates call graphs and puts them into a Kafka topic, requires=*, license=Apache License 2.0]
    14:49:29.674 [main] DEBUG org.pf4j.AbstractPluginManager - Class 'eu.fasten.analyzer.javacgopal.OPALPlugin' for plugin './plugins/javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.674 [main] DEBUG org.pf4j.AbstractPluginManager - Loading plugin './plugins/javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.674 [main] DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.JarPluginLoader@61230f6a' is applicable for plugin './plugins/javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.676 [main] DEBUG org.pf4j.PluginClassLoader - Add 'file:/plugins/javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.677 [main] DEBUG org.pf4j.AbstractPluginManager - Loaded plugin './plugins/javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar' with class loader 'org.pf4j.PluginClassLoader@70e8f8e'
    14:49:29.677 [main] DEBUG org.pf4j.AbstractPluginManager - Creating wrapper for plugin './plugins/javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.678 [main] DEBUG org.pf4j.AbstractPluginManager - Created wrapper 'PluginWrapper [descriptor=PluginDescriptor [pluginId=opal-plugin, pluginClass=eu.fasten.analyzer.javacgopal.OPALPlugin, version=0.0.1, provider=null, dependencies=[], description=Given a Maven coordinate or a file,                                           generates call graphs and puts them into a Kafka topic, requires=*, license=Apache License 2.0], pluginPath=./plugins/javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar]' for plugin './plugins/javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.679 [main] DEBUG org.pf4j.AbstractPluginManager - Use 'org.pf4j.ManifestPluginDescriptorFinder@49b0b76' to find plugins descriptors
    14:49:29.679 [main] DEBUG org.pf4j.AbstractPluginManager - Finding plugin descriptor for plugin './plugins/metadata-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.690 [main] DEBUG org.pf4j.AbstractPluginManager - Found descriptor PluginDescriptor [pluginId=metadata-plugin, pluginClass=eu.fasten.analyzer.metadataplugin.MetadataDatabasePlugin, version=0.0.1, provider=null, dependencies=[], description=Metadata Plugin, requires=*, license=Apache License 2.0]
    14:49:29.690 [main] DEBUG org.pf4j.AbstractPluginManager - Class 'eu.fasten.analyzer.metadataplugin.MetadataDatabasePlugin' for plugin './plugins/metadata-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.690 [main] DEBUG org.pf4j.AbstractPluginManager - Loading plugin './plugins/metadata-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.690 [main] DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.JarPluginLoader@61230f6a' is applicable for plugin './plugins/metadata-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.691 [main] DEBUG org.pf4j.PluginClassLoader - Add 'file:/plugins/metadata-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.691 [main] DEBUG org.pf4j.AbstractPluginManager - Loaded plugin './plugins/metadata-plugin-0.0.1-SNAPSHOT-with-dependencies.jar' with class loader 'org.pf4j.PluginClassLoader@4b0b0854'
    14:49:29.691 [main] DEBUG org.pf4j.AbstractPluginManager - Creating wrapper for plugin './plugins/metadata-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.691 [main] DEBUG org.pf4j.AbstractPluginManager - Created wrapper 'PluginWrapper [descriptor=PluginDescriptor [pluginId=metadata-plugin, pluginClass=eu.fasten.analyzer.metadataplugin.MetadataDatabasePlugin, version=0.0.1, provider=null, dependencies=[], description=Metadata Plugin, requires=*, license=Apache License 2.0], pluginPath=./plugins/metadata-plugin-0.0.1-SNAPSHOT-with-dependencies.jar]' for plugin './plugins/metadata-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.691 [main] DEBUG org.pf4j.AbstractPluginManager - Use 'org.pf4j.ManifestPluginDescriptorFinder@49b0b76' to find plugins descriptors
    14:49:29.691 [main] DEBUG org.pf4j.AbstractPluginManager - Finding plugin descriptor for plugin './plugins/graph-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.703 [main] DEBUG org.pf4j.AbstractPluginManager - Found descriptor PluginDescriptor [pluginId=graph-plugin, pluginClass=eu.fasten.analyzer.graphplugin.GraphDatabasePlugin, version=0.0.1, provider=null, dependencies=[], description=Graph Plugin, requires=*, license=Apache License 2.0]
    14:49:29.703 [main] DEBUG org.pf4j.AbstractPluginManager - Class 'eu.fasten.analyzer.graphplugin.GraphDatabasePlugin' for plugin './plugins/graph-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.703 [main] DEBUG org.pf4j.AbstractPluginManager - Loading plugin './plugins/graph-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.703 [main] DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.JarPluginLoader@61230f6a' is applicable for plugin './plugins/graph-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.703 [main] DEBUG org.pf4j.PluginClassLoader - Add 'file:/plugins/graph-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.704 [main] DEBUG org.pf4j.AbstractPluginManager - Loaded plugin './plugins/graph-plugin-0.0.1-SNAPSHOT-with-dependencies.jar' with class loader 'org.pf4j.PluginClassLoader@353d0772'
    14:49:29.704 [main] DEBUG org.pf4j.AbstractPluginManager - Creating wrapper for plugin './plugins/graph-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.704 [main] DEBUG org.pf4j.AbstractPluginManager - Created wrapper 'PluginWrapper [descriptor=PluginDescriptor [pluginId=graph-plugin, pluginClass=eu.fasten.analyzer.graphplugin.GraphDatabasePlugin, version=0.0.1, provider=null, dependencies=[], description=Graph Plugin, requires=*, license=Apache License 2.0], pluginPath=./plugins/graph-plugin-0.0.1-SNAPSHOT-with-dependencies.jar]' for plugin './plugins/graph-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.704 [main] DEBUG org.pf4j.AbstractPluginManager - Use 'org.pf4j.ManifestPluginDescriptorFinder@49b0b76' to find plugins descriptors
    14:49:29.704 [main] DEBUG org.pf4j.AbstractPluginManager - Finding plugin descriptor for plugin './plugins/pom-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.718 [main] DEBUG org.pf4j.AbstractPluginManager - Found descriptor PluginDescriptor [pluginId=pom-analyzer, pluginClass=eu.fasten.analyzer.pomanalyzer.POMAnalyzerPlugin, version=0.0.1, provider=null, dependencies=[], description=POM Analyzer Plugin, requires=*, license=Apache License 2.0]
    14:49:29.718 [main] DEBUG org.pf4j.AbstractPluginManager - Class 'eu.fasten.analyzer.pomanalyzer.POMAnalyzerPlugin' for plugin './plugins/pom-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.718 [main] DEBUG org.pf4j.AbstractPluginManager - Loading plugin './plugins/pom-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.718 [main] DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.JarPluginLoader@61230f6a' is applicable for plugin './plugins/pom-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.719 [main] DEBUG org.pf4j.PluginClassLoader - Add 'file:/plugins/pom-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.719 [main] DEBUG org.pf4j.AbstractPluginManager - Loaded plugin './plugins/pom-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar' with class loader 'org.pf4j.PluginClassLoader@57c758ac'
    14:49:29.719 [main] DEBUG org.pf4j.AbstractPluginManager - Creating wrapper for plugin './plugins/pom-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.719 [main] DEBUG org.pf4j.AbstractPluginManager - Created wrapper 'PluginWrapper [descriptor=PluginDescriptor [pluginId=pom-analyzer, pluginClass=eu.fasten.analyzer.pomanalyzer.POMAnalyzerPlugin, version=0.0.1, provider=null, dependencies=[], description=POM Analyzer Plugin, requires=*, license=Apache License 2.0], pluginPath=./plugins/pom-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar]' for plugin './plugins/pom-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.720 [main] DEBUG org.pf4j.AbstractPluginManager - Use 'org.pf4j.ManifestPluginDescriptorFinder@49b0b76' to find plugins descriptors
    14:49:29.720 [main] DEBUG org.pf4j.AbstractPluginManager - Finding plugin descriptor for plugin './plugins/repo-cloner-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.728 [main] DEBUG org.pf4j.AbstractPluginManager - Found descriptor PluginDescriptor [pluginId=repo-cloner-plugin, pluginClass=eu.fasten.analyzer.repoclonerplugin.RepoClonerPlugin, version=0.0.1, provider=null, dependencies=[], description=Repository Cloning Plugin, requires=*, license=Apache License 2.0]
    14:49:29.728 [main] DEBUG org.pf4j.AbstractPluginManager - Class 'eu.fasten.analyzer.repoclonerplugin.RepoClonerPlugin' for plugin './plugins/repo-cloner-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.728 [main] DEBUG org.pf4j.AbstractPluginManager - Loading plugin './plugins/repo-cloner-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.728 [main] DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.JarPluginLoader@61230f6a' is applicable for plugin './plugins/repo-cloner-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.729 [main] DEBUG org.pf4j.PluginClassLoader - Add 'file:/plugins/repo-cloner-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.729 [main] DEBUG org.pf4j.AbstractPluginManager - Loaded plugin './plugins/repo-cloner-plugin-0.0.1-SNAPSHOT-with-dependencies.jar' with class loader 'org.pf4j.PluginClassLoader@64cd705f'
    14:49:29.729 [main] DEBUG org.pf4j.AbstractPluginManager - Creating wrapper for plugin './plugins/repo-cloner-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.729 [main] DEBUG org.pf4j.AbstractPluginManager - Created wrapper 'PluginWrapper [descriptor=PluginDescriptor [pluginId=repo-cloner-plugin, pluginClass=eu.fasten.analyzer.repoclonerplugin.RepoClonerPlugin, version=0.0.1, provider=null, dependencies=[], description=Repository Cloning Plugin, requires=*, license=Apache License 2.0], pluginPath=./plugins/repo-cloner-plugin-0.0.1-SNAPSHOT-with-dependencies.jar]' for plugin './plugins/repo-cloner-plugin-0.0.1-SNAPSHOT-with-dependencies.jar'
    14:49:29.730 [main] DEBUG org.pf4j.DependencyResolver - Graph: 
    opal-plugin -> []
    repo-cloner-plugin -> []
    metadata-plugin -> []
    pom-analyzer -> []
    graph-plugin -> []
    14:49:29.731 [main] DEBUG org.pf4j.DependencyResolver - Plugins order: [opal-plugin, repo-cloner-plugin, metadata-plugin, pom-analyzer, graph-plugin]
    14:49:29.731 [main] INFO org.pf4j.AbstractPluginManager - Plugin 'opal-plugin@0.0.1' resolved
    14:49:29.733 [main] INFO org.pf4j.AbstractPluginManager - Plugin 'repo-cloner-plugin@0.0.1' resolved
    14:49:29.733 [main] INFO org.pf4j.AbstractPluginManager - Plugin 'metadata-plugin@0.0.1' resolved
    14:49:29.733 [main] INFO org.pf4j.AbstractPluginManager - Plugin 'pom-analyzer@0.0.1' resolved
    14:49:29.733 [main] INFO org.pf4j.AbstractPluginManager - Plugin 'graph-plugin@0.0.1' resolved
    14:49:29.733 [main] INFO org.pf4j.AbstractPluginManager - Start plugin 'opal-plugin@0.0.1'
    14:49:29.733 [main] DEBUG org.pf4j.DefaultPluginFactory - Create instance for plugin 'eu.fasten.analyzer.javacgopal.OPALPlugin'
    14:49:29.754 [main] INFO org.pf4j.AbstractPluginManager - Start plugin 'repo-cloner-plugin@0.0.1'
    14:49:29.754 [main] DEBUG org.pf4j.DefaultPluginFactory - Create instance for plugin 'eu.fasten.analyzer.repoclonerplugin.RepoClonerPlugin'
    14:49:29.760 [main] INFO org.pf4j.AbstractPluginManager - Start plugin 'metadata-plugin@0.0.1'
    14:49:29.760 [main] DEBUG org.pf4j.DefaultPluginFactory - Create instance for plugin 'eu.fasten.analyzer.metadataplugin.MetadataDatabasePlugin'
    14:49:29.771 [main] INFO org.pf4j.AbstractPluginManager - Start plugin 'pom-analyzer@0.0.1'
    14:49:29.771 [main] DEBUG org.pf4j.DefaultPluginFactory - Create instance for plugin 'eu.fasten.analyzer.pomanalyzer.POMAnalyzerPlugin'
    14:49:29.783 [main] INFO org.pf4j.AbstractPluginManager - Start plugin 'graph-plugin@0.0.1'
    14:49:29.783 [main] DEBUG org.pf4j.DefaultPluginFactory - Create instance for plugin 'eu.fasten.analyzer.graphplugin.GraphDatabasePlugin'
    14:49:29.797 [main] DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions from plugin 'opal-plugin'
    14:49:29.798 [main] DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storages from classpath
    14:49:29.799 [main] DEBUG org.pf4j.LegacyExtensionFinder - Read 'file:/server-0.0.1-SNAPSHOT-with-dependencies.jar!/META-INF/extensions.idx'
    14:49:29.805 [main] DEBUG org.pf4j.AbstractExtensionFinder - No extensions found
    14:49:29.805 [main] DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storages from plugins
    14:49:29.806 [main] DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storage from plugin 'opal-plugin'
    14:49:29.806 [main] DEBUG org.pf4j.LegacyExtensionFinder - Read 'META-INF/extensions.idx'
    14:49:29.807 [main] DEBUG org.pf4j.AbstractExtensionFinder - Found possible 1 extensions:
    14:49:29.808 [main] DEBUG org.pf4j.AbstractExtensionFinder -    eu.fasten.analyzer.javacgopal.OPALPlugin$OPAL
    14:49:29.808 [main] DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storage from plugin 'repo-cloner-plugin'
    14:49:29.808 [main] DEBUG org.pf4j.LegacyExtensionFinder - Read 'META-INF/extensions.idx'
    14:49:29.809 [main] DEBUG org.pf4j.AbstractExtensionFinder - Found possible 1 extensions:
    14:49:29.809 [main] DEBUG org.pf4j.AbstractExtensionFinder -    eu.fasten.analyzer.repoclonerplugin.RepoClonerPlugin$RepoCloner
    14:49:29.809 [main] DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storage from plugin 'metadata-plugin'
    14:49:29.809 [main] DEBUG org.pf4j.LegacyExtensionFinder - Read 'META-INF/extensions.idx'
    14:49:29.810 [main] DEBUG org.pf4j.AbstractExtensionFinder - Found possible 1 extensions:
    14:49:29.810 [main] DEBUG org.pf4j.AbstractExtensionFinder -    eu.fasten.analyzer.metadataplugin.MetadataDatabasePlugin$MetadataDBExtension
    14:49:29.810 [main] DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storage from plugin 'pom-analyzer'
    14:49:29.810 [main] DEBUG org.pf4j.LegacyExtensionFinder - Read 'META-INF/extensions.idx'
    14:49:29.811 [main] DEBUG org.pf4j.AbstractExtensionFinder - Found possible 1 extensions:
    14:49:29.811 [main] DEBUG org.pf4j.AbstractExtensionFinder -    eu.fasten.analyzer.pomanalyzer.POMAnalyzerPlugin$POMAnalyzer
    14:49:29.811 [main] DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storage from plugin 'graph-plugin'
    14:49:29.812 [main] DEBUG org.pf4j.LegacyExtensionFinder - Read 'META-INF/extensions.idx'
    14:49:29.813 [main] DEBUG org.pf4j.AbstractExtensionFinder - Found possible 1 extensions:
    14:49:29.813 [main] DEBUG org.pf4j.AbstractExtensionFinder -    eu.fasten.analyzer.graphplugin.GraphDatabasePlugin$GraphDBExtension
    14:49:29.813 [main] DEBUG org.pf4j.AbstractExtensionFinder - Loading class 'eu.fasten.analyzer.javacgopal.OPALPlugin$OPAL' using class loader 'org.pf4j.PluginClassLoader@70e8f8e'
    14:49:29.817 [main] DEBUG org.pf4j.AbstractExtensionFinder - Added extension 'eu.fasten.analyzer.javacgopal.OPALPlugin$OPAL' with ordinal 0
    14:49:29.818 [main] DEBUG org.pf4j.AbstractExtensionFinder - Found 1 extensions for plugin 'opal-plugin'
    14:49:29.818 [main] DEBUG org.pf4j.DefaultExtensionFactory - Create instance for extension 'eu.fasten.analyzer.javacgopal.OPALPlugin$OPAL'
    java.lang.NullPointerException
        at eu.fasten.server.FastenServer.lambda$run$1(FastenServer.java:138)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at eu.fasten.server.FastenServer.run(FastenServer.java:140)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at eu.fasten.server.FastenServer.main(FastenServer.java:304)
    ```
    </details>
- `kubectl --namespace fasten describe pod fasten-server`
    ```
    [...]
    Containers:
    fasten-server:
        Last State:     Terminated
        Reason:       Error
        Exit Code:    1
    ```

**Comment by proksch** [comment]
Did we ignore this issue long enough to fix the underlying problem? :D

**Comment by mir-am** [comment]
> Did we ignore this issue long enough to fix the underlying problem? :D

This is not a major issue. The FASTEN server returns NPE if no CLI args are passed, e.g., name of the plugin to run. That said, we can handle this by showing a custom message.

**Comment by proksch** [comment]
This is probably the worst possible handling for a faulty input. :)

Please add a simple check. It is fine to just throw an exception during startup, but please provide a hint in the error message that describes how to fix it, e.g., "No plugin selected for execution, quitting..."

**Comment by mir-am** [comment]
I'll solve this issue in another PR.

**Comment by proksch** [comment]
Not sure if this problem has ever been fixed, but a) this should be pretty straight-forward to detect in practice and b) the old server infrastructure will be replaced soon. As such, I will close the issue.
