### ISSUE TITLE
Getting org.dom4j.InvalidXPathException when trying to generate org.slf4j:slf4j-api:1.7.29 call graph

### ISSUE THREAD

**Issue by tmortagne** [fasten-project/fasten#29]
version: [#4ee04b4321830d41d61dc93ab2e290026469411f](https://github.com/fasten-project/fasten/tree/4ee04b4321830d41d61dc93ab2e290026469411f) (May 22, 2020)

Built with Java 11.0.7 with `mvn install`.

I execute the command given as example in the [README file](https://github.com/fasten-project/fasten/tree/4ee04b4321830d41d61dc93ab2e290026469411f/analyzer/javacg-wala#examples) and get the following result:

```
$ java -jar docker/plugins/javacg-wala-0.0.1-SNAPSHOT-with-dependencies.jar -jre /media/DATA/utils/jdk8 -c org.slf4j:slf4j-api:1.7.29 --stdout
[main] INFO eu.fasten.analyzer.javacgwala.Main - Could not load wala.properties
[main] INFO eu.fasten.analyzer.javacgwala.data.callgraph.CallGraphConstructor - Generating call graph for the Maven coordinate using WALA: org.slf4j:slf4j-api:1.7.29
WARNING: java_runtime_dir /Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home in wala.properties is invalid.  Using boot class path instead.
[main] INFO eu.fasten.analyzer.javacgwala.data.callgraph.CallGraphConstructor - Generated the call graph in 4.379 seconds.
[main] INFO eu.fasten.analyzer.javacgwala.data.callgraph.analyzer.WalaResultAnalyzer - Wrapping call graph with 4848 nodes...
[main] INFO eu.fasten.analyzer.javacgwala.data.callgraph.analyzer.WalaResultAnalyzer - Wrapped call graph in 0.497 seconds [Internal calls: 345, External calls: 219]
[main] ERROR eu.fasten.analyzer.javacgwala.Main - Failed to generate a call graph for Maven coordinate: org.slf4j:slf4j-api:1.7.29, Error: {}
org.dom4j.InvalidXPathException: Invalid XPath expression: ./*[local-name() ='properties'] org.jaxen.saxpath.base.XPathReader
	at org.dom4j.xpath.DefaultXPath.parse(DefaultXPath.java:355)
	at org.dom4j.xpath.DefaultXPath.<init>(DefaultXPath.java:59)
	at org.dom4j.DocumentFactory.createXPath(DocumentFactory.java:222)
	at org.dom4j.tree.AbstractNode.createXPath(AbstractNode.java:202)
	at org.dom4j.tree.AbstractNode.selectSingleNode(AbstractNode.java:178)
	at eu.fasten.analyzer.baseanalyzer.MavenCoordinate$MavenResolver.getDependencies(MavenCoordinate.java:182)
	at eu.fasten.analyzer.baseanalyzer.MavenCoordinate$MavenResolver.resolveDependencies(MavenCoordinate.java:160)
	at eu.fasten.analyzer.javacgwala.data.callgraph.PartialCallGraph.createExtendedRevisionCallGraph(PartialCallGraph.java:128)
	at eu.fasten.analyzer.javacgwala.Main.run(Main.java:179)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
	at picocli.CommandLine.execute(CommandLine.java:1864)
	at eu.fasten.analyzer.javacgwala.Main.main(Main.java:133)

```

Maybe `mvn install` is not enough and it needs some other parameter ?

Here is the build log

```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for eu.fasten.analyzer:javacg-wala:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-compiler-plugin @ eu.fasten:parent:0.0.1-SNAPSHOT, /media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/pom.xml, line 86, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] -------------------< eu.fasten.analyzer:javacg-wala >-------------------
[INFO] Building javacg-wala 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ javacg-wala ---
[INFO] Deleting /media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/analyzer/javacg-wala/target
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (default) @ javacg-wala ---
[INFO] argLine set to -javaagent:/home/tmortagne/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/analyzer/javacg-wala/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ javacg-wala ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ javacg-wala ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 14 source files to /media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/analyzer/javacg-wala/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ javacg-wala ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ javacg-wala ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/analyzer/javacg-wala/target/test-classes
[INFO] /media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/analyzer/javacg-wala/src/test/java/eu/fasten/analyzer/javacgwala/WALAPluginTest.java: /media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/analyzer/javacg-wala/src/test/java/eu/fasten/analyzer/javacgwala/WALAPluginTest.java uses unchecked or unsafe operations.
[INFO] /media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/analyzer/javacg-wala/src/test/java/eu/fasten/analyzer/javacgwala/WALAPluginTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ javacg-wala ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running eu.fasten.analyzer.javacgwala.WALAPluginTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.003 s - in eu.fasten.analyzer.javacgwala.WALAPluginTest
[INFO] Running eu.fasten.analyzer.javacgwala.data.ArtifactResolverTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in eu.fasten.analyzer.javacgwala.data.ArtifactResolverTest
[INFO] Running eu.fasten.analyzer.javacgwala.data.core.MethodTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s - in eu.fasten.analyzer.javacgwala.data.core.MethodTest
[INFO] Running eu.fasten.analyzer.javacgwala.data.callgraph.WalaResultAnalyzerTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in eu.fasten.analyzer.javacgwala.data.callgraph.WalaResultAnalyzerTest
[INFO] Running eu.fasten.analyzer.javacgwala.data.callgraph.PartialCallGraphTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in eu.fasten.analyzer.javacgwala.data.callgraph.PartialCallGraphTest
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 5, Failures: 0, Errors: 0, Skipped: 5
[INFO] 
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.2:report (report) @ javacg-wala ---
[INFO] Loading execution data file /media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/analyzer/javacg-wala/target/jacoco.exec
[INFO] Analyzed bundle 'javacg-wala' with 18 classes
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ javacg-wala ---
[INFO] Building jar: /media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/analyzer/javacg-wala/target/javacg-wala-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-shade-plugin:3.2.1:shade (default) @ javacg-wala ---
[INFO] Including eu.fasten:core:jar:0.0.1-SNAPSHOT in the shaded jar.
[INFO] Including it.unimi.dsi:dsiutils:jar:2.6.0 in the shaded jar.
[INFO] Including it.unimi.dsi:fastutil:jar:8.2.3 in the shaded jar.
[INFO] Including com.martiansoftware:jsap:jar:2.1 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:28.0-jre in the shaded jar.
[INFO] Including com.google.guava:failureaccess:jar:1.0.1 in the shaded jar.
[INFO] Including com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava in the shaded jar.
[INFO] Including com.google.code.findbugs:jsr305:jar:3.0.2 in the shaded jar.
[INFO] Including org.checkerframework:checker-qual:jar:2.8.1 in the shaded jar.
[INFO] Including com.google.errorprone:error_prone_annotations:jar:2.3.2 in the shaded jar.
[INFO] Including com.google.j2objc:j2objc-annotations:jar:1.3 in the shaded jar.
[INFO] Including org.codehaus.mojo:animal-sniffer-annotations:jar:1.17 in the shaded jar.
[INFO] Including commons-configuration:commons-configuration:jar:1.10 in the shaded jar.
[INFO] Including commons-lang:commons-lang:jar:2.6 in the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.1.1 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:2.6 in the shaded jar.
[INFO] Including commons-collections:commons-collections:jar:20040616 in the shaded jar.
[INFO] Including org.apache.commons:commons-math3:jar:3.6.1 in the shaded jar.
[INFO] Including it.unimi.dsi:webgraph:jar:3.6.3 in the shaded jar.
[INFO] Including it.unimi.dsi:sux4j:jar:5.0.4 in the shaded jar.
[INFO] Including net.sf.jung:jung-api:jar:2.1.1 in the shaded jar.
[INFO] Including net.sf.jung:jung-io:jar:2.1.1 in the shaded jar.
[INFO] Including net.sf.jung:jung-algorithms:jar:2.1.1 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.9 in the shaded jar.
[INFO] Including org.eclipse.jgit:org.eclipse.jgit:jar:5.2.1.201812262042-r in the shaded jar.
[INFO] Including com.jcraft:jsch:jar:0.1.54 in the shaded jar.
[INFO] Including com.jcraft:jzlib:jar:1.1.1 in the shaded jar.
[INFO] Including com.googlecode.javaewah:JavaEWAH:jar:1.1.6 in the shaded jar.
[INFO] Including org.json:json:jar:20180813 in the shaded jar.
[INFO] Including org.apache.kafka:kafka-clients:jar:2.3.0 in the shaded jar.
[INFO] Including com.github.luben:zstd-jni:jar:1.4.0-1 in the shaded jar.
[INFO] Including org.lz4:lz4-java:jar:1.6.0 in the shaded jar.
[INFO] Including org.xerial.snappy:snappy-java:jar:1.1.7.3 in the shaded jar.
[INFO] Including com.esotericsoftware:kryo:jar:5.0.0-RC4 in the shaded jar.
[INFO] Including com.esotericsoftware:reflectasm:jar:1.11.8 in the shaded jar.
[INFO] Including com.esotericsoftware:minlog:jar:1.3.1 in the shaded jar.
[INFO] Including org.rocksdb:rocksdbjni:jar:6.2.4 in the shaded jar.
[INFO] Including org.jooq:jooq:jar:3.12.3 in the shaded jar.
[INFO] Including org.reactivestreams:reactive-streams:jar:1.0.2 in the shaded jar.
[INFO] Including javax.xml.bind:jaxb-api:jar:2.3.0 in the shaded jar.
[INFO] Including eu.fasten.analyzer:base-analyzer:jar:0.0.1-SNAPSHOT in the shaded jar.
[INFO] Including com.ibm.wala:com.ibm.wala.core:jar:1.5.5 in the shaded jar.
[INFO] Including com.ibm.wala:com.ibm.wala.util:jar:1.5.5 in the shaded jar.
[INFO] Including com.ibm.wala:com.ibm.wala.shrike:jar:1.5.5 in the shaded jar.
[INFO] Including info.picocli:picocli:jar:4.0.4 in the shaded jar.
[INFO] Including org.gradle:gradle-tooling-api:jar:4.3 in the shaded jar.
[INFO] Including org.slf4j:slf4j-simple:jar:1.7.30 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.30 in the shaded jar.
[INFO] Including org.objenesis:objenesis:jar:2.6 in the shaded jar.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] picocli-4.0.4.jar, base-analyzer-0.0.1-SNAPSHOT.jar define 1 overlapping classes: 
[WARNING]   - META-INF.versions.9.module-info
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Attaching shaded artifact.
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ javacg-wala ---
[INFO] Installing /media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/analyzer/javacg-wala/target/javacg-wala-0.0.1-SNAPSHOT.jar to /home/tmortagne/.m2/repository/eu/fasten/analyzer/javacg-wala/0.0.1-SNAPSHOT/javacg-wala-0.0.1-SNAPSHOT.jar
[INFO] Installing /media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/analyzer/javacg-wala/pom.xml to /home/tmortagne/.m2/repository/eu/fasten/analyzer/javacg-wala/0.0.1-SNAPSHOT/javacg-wala-0.0.1-SNAPSHOT.pom
[INFO] Installing /media/DATA/xwiki/xwikisas/research/FASTEN/github/fasten-fork/analyzer/javacg-wala/docker/plugins/javacg-wala-0.0.1-SNAPSHOT-with-dependencies.jar to /home/tmortagne/.m2/repository/eu/fasten/analyzer/javacg-wala/0.0.1-SNAPSHOT/javacg-wala-0.0.1-SNAPSHOT-with-dependencies.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.340 s
[INFO] Finished at: 2020-06-08T15:44:56+02:00
[INFO] ------------------------------------------------------------------------
```

Built with Maven 3.6.3.

**Comment by ashkboos** [comment]
This is because when we want to build the generator plugins inside the plugin folder it can not find the dependencies that are declared in the base analyzer or server plugin. If we do `mvn install` in the parent it does the job, but inside each plugin we have to manually add those dependencies each time. Do you know any alternative other than manually adding those dependencies?

**Comment by tmortagne** [comment]
@ashkboos so it looks like this problem is caused by some weird use of `<scope>provided</provided>` (none of them really make sense to me since they make some of the modules pretty much unusable as dependency and they cause conflicts which are what seems to loose Maven) and cleaning them seems to be enough to fix the problem.
Also IMO none of the parent pom should contain <dependencies>, I understand the reflex but it just makes each module descriptor harder to understand, I usually find much safer to just declare the dependencies you need (when they don't already come from another dependency) right in the pom of the module itself.

**Comment by ilyagrishkov** [comment]
We have cleaned pom.xml files across the entire project, so now there should be less dependency problems. The only dependencies that are coming from parent modules are test related ones (jUnit, Mockito) as well as dependencies for the logger. Those are universal for every single module of the project, so it made sense to put them into the root pom.xml. Other that that, modules now have their own dependencies (unless they already come from other dependencies). 
Thank you for the advice.
