### ISSUE TITLE
JavaCGOPAL container fails to run

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten#349]
## Describe the bug
After recent changes to JavaCGOPAL its container does not properly run anymore. There are errors in the log (see below) on header fields and manifests. The final log line are:
```
[2021-11-30 20:54:25,320] [INFO ] [main] [e.f.s.FastenServer] - Plugin init done: 0 KafkaPlugins, 0 DB plug-ins, 0 GraphDB plug-ins: 0 total plugins
[2021-11-30 20:54:25,325] [INFO ] [main] [e.f.s.FastenServer] - No DB connection info provided, skipping initialization.
```
which is especially weird since I don't think that JavaCGOpal connects to the DB.

## To Reproduce
1. `docker pull ghcr.io/fasten-project/fasten/fasten.server.develop.slim:latest`
2. `FASTEN_MVN_REPO=https://repo.maven.apache.org/maven2/ docker run ghcr.io/fasten-project/fasten/fasten.server.develop.slim:latest -k localhost:9092 -cg OPALPlugin_2 -pl OPAL -kt OPAL=fasten.POMAnalyzer.out -po OPAL=/tmp/revision-callgraphs`

## Logs
```
[2021-11-30 20:28:45,428] [INFO ] [main] [e.f.s.FastenServer] - Plugin init done: 0 KafkaPlugins, 0 DB plug-ins, 0 GraphDB plug-ins: 0 total plugins
[2021-11-30 20:28:45,429] [INFO ] [main] [e.f.s.FastenServer] - No DB connection info provided, skipping initialization.
[2021-11-30 20:28:48,945] [INFO ] [main] [e.f.s.FastenServer] - FASTEN server started in development mode
[2021-11-30 20:28:48,957] [INFO ] [main] [e.f.s.FastenServer] - ************************System Info***************************
[2021-11-30 20:28:49,004] [INFO ] [main] [e.f.s.FastenServer] - Max Heap size: 4294967296 Bytes
[2021-11-30 20:28:49,004] [INFO ] [main] [e.f.s.FastenServer] - **************************************************************
[2021-11-30 20:28:49,056] [INFO ] [main] [o.p.DefaultPluginStatusProvider] - Enabled plugins: []
[2021-11-30 20:28:49,059] [INFO ] [main] [o.p.DefaultPluginStatusProvider] - Disabled plugins: []
[2021-11-30 20:28:49,078] [INFO ] [main] [o.p.DefaultPluginManager] - PF4J version 0.0.0 in 'deployment' mode
[2021-11-30 20:28:49,079] [DEBUG] [main] [o.p.AbstractPluginManager] - Lookup plugins in './plugins'
[2021-11-30 20:28:49,082] [DEBUG] [main] [o.p.AbstractPluginManager] - Found 14 possible plugins: [./plugins/javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/metadata-plugin-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/callable-index-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/pom-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/repo-cloner-plugin-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/quality-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/vulnerability-consumer-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/repo-analyzer-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/vulnerability-cache-invalidation-plugin-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/parallel-vulnerability-cache-invalidation-plugin-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/vulnerability-cache-processor-plugin-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/vulnerability-statements-processor-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/vulnerability-packages-listener-0.0.1-SNAPSHOT-with-dependencies.jar, ./plugins/dummy-plugin-0.0.1-SNAPSHOT-with-dependencies.jar]
[2021-11-30 20:28:49,083] [DEBUG] [main] [o.p.AbstractPluginManager] - Use 'org.pf4j.ManifestPluginDescriptorFinder@12d4bf7e' to find plugins descriptors
[2021-11-30 20:28:49,084] [DEBUG] [main] [o.p.AbstractPluginManager] - Finding plugin descriptor for plugin './plugins/javacg-opal-0.0.1-SNAPSHOT-with-dependencies.jar'
[2021-11-30 20:28:49,163] [ERROR] [main] [o.p.AbstractPluginManager] - java.io.IOException: invalid header field
org.pf4j.PluginRuntimeException: java.io.IOException: invalid header field
	at org.pf4j.ManifestPluginDescriptorFinder.readManifest(ManifestPluginDescriptorFinder.java:69)
	at org.pf4j.ManifestPluginDescriptorFinder.find(ManifestPluginDescriptorFinder.java:56)
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:812)
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:130)
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:224)
	at eu.fasten.server.FastenServer.loadAndStartAllPlugins(FastenServer.java:230)
	at eu.fasten.server.FastenServer.run(FastenServer.java:177)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at eu.fasten.server.FastenServer.main(FastenServer.java:435)
Caused by: java.io.IOException: invalid header field
	at java.base/java.util.jar.Attributes.read(Unknown Source)
	at java.base/java.util.jar.Manifest.read(Unknown Source)
	at java.base/java.util.jar.Manifest.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.getManifestFromReference(Unknown Source)
	at java.base/java.util.jar.JarFile.getManifest(Unknown Source)
	at org.pf4j.ManifestPluginDescriptorFinder.readManifest(ManifestPluginDescriptorFinder.java:64)
	... 14 common frames omitted
```

## Environment (please complete the following information):
 - OS: MacOS & Linux 
 - Java version: 11

**Comment by proksch** [comment]
This is really surprising, as I did not touch the Manifest, but I will investigate this tomorrow.

**Comment by proksch** [comment]
My only change that has the potential to explain startup issues is the removal of duplicate dependency declarations in the different profiles of the OPAL pom.xml (https://github.com/fasten-project/fasten/commit/9b815dee42684593bf3957fcc7fee3794b84c0d5#diff-f494db1613925932b2a66c9ee650e555f99e5d4ff0c543c6dfd8da9bf768caa0)... I do not understand why this would cause issues as the declared dependencies in profiles should be merged with the dependencies in the main section, so -to the best of my Maven understanding- the change should not make any difference apart from removing redundancy.

I will dig a bit deeper into the startup and deployment of the plugins next to get better information about what causes this issue.
