### ISSUE TITLE
Java Metadata Plugin has stopped processing records

### ISSUE THREAD

**Issue by gdrosos** [fasten-project/fasten#480]
## Describe the bug
When observing the priority topics on the Java pipeline, I noticed that only 2% ( 4,164 out of 368,265 records) of the OPAL priority topic records have been consumed by the Metadata Java Plugin. To further investigate the issue, I noticed from observing k8s that the  Java Metadata Plugin pod has crashed (CrashLoopBackOff). 
I am attatching logs of the failed pods. 

## Logs
```
[2022-07-13 16:06:58,195] [INFO ] [main] [e.f.s.p.k.FastenKafkaPlugin] - Read priority message offset 125 from partition 57.
[2022-07-13 16:06:58,210] [ERROR] [main] [e.f.s.p.k.FastenKafkaPlugin] - Trying to store the hash of a record, but failed due to an IOException
java.io.IOException: Permission denied
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(Unknown Source)
	at eu.fasten.server.plugins.kafka.LocalStorage.store(LocalStorage.java:104)
	at eu.fasten.server.plugins.kafka.FastenKafkaPlugin.processRecord(FastenKafkaPlugin.java:328)
	at eu.fasten.server.plugins.kafka.FastenKafkaPlugin.handleConsuming(FastenKafkaPlugin.java:240)
	at eu.fasten.server.plugins.kafka.FastenKafkaPlugin.run(FastenKafkaPlugin.java:168)
	at eu.fasten.server.plugins.kafka.FastenKafkaPlugin.start(FastenKafkaPlugin.java:206)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at eu.fasten.server.FastenServer.run(FastenServer.java:202)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at eu.fasten.server.FastenServer.main(FastenServer.java:435)
[2022-07-13 16:07:01,229] [INFO ] [main] [o.a.k.c.u.AppInfoParser] - App info kafka.consumer for eu.fasten.analyzer.metadataplugin.MetadataDatabaseJavaPlugin.MetadataDBJavaExtension_client_priority unregistered
[2022-07-13 16:07:01,229] [INFO ] [main] [e.f.s.p.k.FastenKafkaPlugin] - Plugin Metadata plugin stopped gracefully
Exception in thread "main" java.lang.StackOverflowError
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:880)
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:901)
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:880)
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:901)
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:880)
	at org.jooq.impl.Expression.acceptAssociative(Expression.java:901)
```

**Comment by mir-am** [comment]
Sorry for the late response. I will investigate the issue.

**Comment by mir-am** [comment]
@gdrosos 
I've fixed the metadata plugin issue by fixing folder permissions in the `local_storage` folder. The folders should be owned by the `fasten` user, not `root`.

**Comment by mir-am** [comment]
> Thank you very much @mir-am! By the way the maven dependency graph resolver plugin has also stoped working: [fasten-project/data-processing#24](https://github.com/fasten-project/data-processing/issues/24)

It was not progessing because of the Kafka disconnect exception. I have restarted the plugin to see whether it resolves its progress issue or not.

**Comment by gdrosos** [comment]
Thanks @mir-am for the fix! I can confirm that the Java Metadata Plugin now consumes properly the records.
