### ISSUE TITLE
NullPointerException when generating the JSON string of the call graph of a specific Maven coordinate

### ISSUE THREAD

**Issue by mir-am** [fasten-project/fasten#7]
The following Maven coordinate produces an unhandled NullPointerException:
```
ch.epfl.scala:collection-strawman_0.6:0.8.0
```
The stack trace for the issue is as follows:
```
java.lang.NullPointerException
	at eu.fasten.analyzer.javacgopal.data.callgraph.ExtendedRevisionCallGraph.toListOfString(ExtendedRevisionCallGraph.java:174)
	at eu.fasten.analyzer.javacgopal.data.callgraph.ExtendedRevisionCallGraph.lambda$toJSON$5(ExtendedRevisionCallGraph.java:158)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at eu.fasten.analyzer.javacgopal.data.callgraph.ExtendedRevisionCallGraph.toJSON(ExtendedRevisionCallGraph.java:152)
	at eu.fasten.analyzer.javacgopal.Main.run(Main.java:123)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
	at picocli.CommandLine.execute(CommandLine.java:1864)
	at eu.fasten.analyzer.javacgopal.Main.main(Main.java:136)
```
I temporarily patched the issue in 0b47f9e0aa492d9a01cab452525f041f7c2e3fb4 by adding a null pointer check in `toListOfString` method. The issue is that the FASTEN URIs of a type's methods are null and causes the described issue. I think that we should investigate this issue more and find out why a type has methods but its methods have not FASTEN URIs.

## Reproduce the issue

1- Remove the null pointer check at https://github.com/fasten-project/fasten/blob/c9d73f106ddd808fab7cbdcf94167201a018eb5f/analyzer/javacg-opal/src/main/java/eu/fasten/analyzer/javacgopal/data/callgraph/ExtendedRevisionCallGraph.java#L174
2- Run the Main class of the OPAL plug-in with the given Maven coordinate.

**Comment by ilyagrishkov** [comment]
New version of OPAL (V3) throws a BytecodeProcessingFailedException, because one method has an unknown access flag. 
We cannot fix it.
